//
//  OpenCodeProfileEditorView.swift
//  AgentConfig
//

import SwiftUI

struct OpenCodeProfileEditorView: View {

    @ObservedObject var viewModel: OpenCodeProfileViewModel

    var body: some View {
        AgentProfileEditorView(profile: editorProfile)
    }

    private var editorProfile: AgentProfileEditorProfile? {
        guard let profile = viewModel.selectedProfile else { return nil }

        return AgentProfileEditorProfile(
            id: profile.id,
            name: profile.name,
            nameMaxLength: viewModel.profileNameMaxLength,
            status: profileStatus(for: profile),
            canDelete: viewModel.profiles.count > 1,
            deleteConfirmation: AgentProfileEditorDeleteConfirmation(
                title: L10n.tr("opencode.deleteConfirmation.title", value: "Delete OpenCode Profile?"),
                message: L10n.format("opencode.deleteConfirmation.message", value: "“%@” will be deleted. This will not modify any OpenCode config files already written to disk.", displayName(for: profile.name))
            ),
            fields: [
                AgentProfileEditorField(
                    id: "config",
                    title: "~/.config/opencode/opencode.json",
                    language: "JSON",
                    helpText: L10n.tr("opencode.field.config.help", value: "OpenCode global config file. Applying writes the full contents to ~/.config/opencode/opencode.json."),
                    fileType: .json,
                    accentColor: Color(red: 0.18, green: 0.64, blue: 0.42),
                    defaultHeight: 220,
                    text: Binding(
                        get: { viewModel.profiles.first { $0.id == profile.id }?.configText ?? "" },
                        set: { viewModel.updateSelected(configText: $0) }
                    ),
                    persistedHeight: profile.configEditorHeight,
                    onPersistHeight: { viewModel.updateSelectedEditorHeight(configEditorHeight: $0) }
                ),
                AgentProfileEditorField(
                    id: "auth",
                    title: "~/.local/share/opencode/auth.json",
                    language: "JSON",
                    helpText: L10n.tr("opencode.field.auth.help", value: "OpenCode credential file. It is commonly generated by /connect, but you can also manage the full auth.json contents here."),
                    fileType: .json,
                    accentColor: Color(red: 0.15, green: 0.42, blue: 0.89),
                    defaultHeight: 150,
                    text: Binding(
                        get: { viewModel.profiles.first { $0.id == profile.id }?.authText ?? "" },
                        set: { viewModel.updateSelected(authText: $0) }
                    ),
                    persistedHeight: profile.authEditorHeight,
                    onPersistHeight: { viewModel.updateSelectedEditorHeight(authEditorHeight: $0) }
                ),
                AgentProfileEditorField(
                    id: "zshrc",
                    title: "~/.zshrc",
                    language: "Shell",
                    helpText: L10n.tr("opencode.field.zshrc.help", value: "Only manages the AgentConfig OpenCode Profile block and will not overwrite the full ~/.zshrc."),
                    fileType: .shell,
                    accentColor: Color(red: 0.46, green: 0.40, blue: 0.90),
                    defaultHeight: 150,
                    text: Binding(
                        get: { viewModel.profiles.first { $0.id == profile.id }?.zshrcText ?? "" },
                        set: { viewModel.updateSelected(zshrcText: $0) }
                    ),
                    persistedHeight: profile.zshrcEditorHeight,
                    onPersistHeight: { viewModel.updateSelectedEditorHeight(zshrcEditorHeight: $0) }
                )
            ],
            updateName: { viewModel.updateSelected(name: $0) },
            delete: {
                if viewModel.deleteProfile(id: profile.id) {
                    return .success(L10n.tr("profile.deleted", value: "Profile deleted"))
                }
                return .failure(viewModel.lastErrorMessage ?? L10n.tr("profile.deleteFailed", value: "Delete failed"))
            },
            apply: {
                let success = await viewModel.applySelected()
                if success {
                    return .success(L10n.tr("profile.applied", value: "Profile applied"))
                }
                return .failure(viewModel.lastErrorMessage ?? L10n.tr("profile.applyFailed", value: "Apply failed"))
            }
        )
    }

    private func profileStatus(for profile: OpenCodeProfile) -> AgentProfileEditorStatus {
        if profile.isDirty {
            return AgentProfileEditorStatus(text: L10n.tr("profile.status.modified", value: "Unapplied Changes"), color: .orange)
        }
        if profile.isActive && viewModel.isDiskOutOfSync {
            return AgentProfileEditorStatus(text: L10n.tr("profile.status.external", value: "External Changes"), color: .red)
        }
        if profile.isActive {
            return AgentProfileEditorStatus(text: L10n.tr("profile.status.active", value: "Active"), color: .green)
        }
        return AgentProfileEditorStatus(text: L10n.tr("profile.status.ready", value: "Ready to Apply"), color: .secondary)
    }

    private func displayName(for name: String) -> String {
        name.isEmpty ? L10n.tr("profile.defaultName", value: "Untitled Profile") : name
    }
}
